### ISSUE TITLE
No "Access-Control-Allow-Origin" problem with DarkSky, GMail

### ISSUE THREAD

**Issue by lawrenceadams** [pschfr/Start#10]
Hey,

I'm not sure if its just me this is happening to ~ but do you know how to get around the "No 'Access-Control-Allow-Origin' header is present on the requested resource" errors that are thrown by both _GMail_ and the _DarkSky_ functions?

Cheers,
    L

**Comment by lawrenceadams** [comment]
This is the way I got around the problem (jQuery with JSONP AJAX request): https://github.com/lozinge/start/blob/gh-pages/src/script.js#L187-L194

**Comment by pschfr** [comment]
This is kinda out of scope, as this a browser-introduced limitation. What you can do, is route the requests through a PHP proxy such as [cowboy/php-simple-proxy](https://github.com/cowboy/php-simple-proxy).
